=== utkarshshobhari/tour-planner/guide.dtd
<!ELEMENT destinations (destination+)>
<!ELEMENT destination (name,location,estimatedCost,durationHours)>
<!ATTLIST destination id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT estimatedCost (#PCDATA)>
<!ELEMENT durationHours (#PCDATA)>

=== utkarshshobhari/tour-planner/new.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="newstyyle.xsl"?>
<!DOCTYPE destinations SYSTEM "guide.dtd">
<destinations>
    <destination id="D001">
        <name>Paris</name>
        <location>France</location>
        <estimatedCost>20</estimatedCost>
        <durationHours>5</durationHours>
    </destination>
    <destination id="D002">
        <name>London</name>
        <location>United Kingdom</location>
        <estimatedCost>10</estimatedCost>
        <durationHours>15</durationHours>
    </destination>
    <destination id="D003">
        <name>Bangkok</name>
        <location>Thailand</location>
        <estimatedCost>12</estimatedCost>
        <durationHours>3</durationHours>
    </destination>
</destinations>
